module.exports.items = [
	'lays',
	'samsung s21',
	'asus GTX 3060',
	'seiko premium 5',
	'logitech G304',
	'asus notebook G503VD',
	'Nike cotton socks',
	'EUOW Men Hawaiian Shirt Short',
	'SAMSUNG (MZ-V8V1T0B/AM) 980 SSD 1TB',
	'Pokémon Assorted Cards',
	'Olympia Luggage Rolling Shopper Tote,Black',
	'Travelpro Crew Versapack Deluxe Tote Bag',
	'Server 2019 Standard 16 Core | Version 1809',
	'SOUND FORGE Audio Studio 15',
	'Ultra Premium Clumping Cat Litter',
	'TetraMin Plus Tropical Flakes, Cleaner and Clearer Water Formula',
	'Kona Cotton White, Quilting Fabric by the Yard',
	'Angelus 2-Soft Fabric Medium 4 oz',
	'LG 24M47VQ 24-Inch LED-lit Monitor, Black',
	'Dell SE2422HX - 23.8-inch FHD (1920 x 1080) 16:9 Monitor'
];

module.exports.categories = [
	'Accessories and Supplies',
	'Camera and Photo',
	'Car and Vehicle Electronics',
	'Cell Phone and Accessories',
	'Computers and Accessories',
	'GPS and Navigation',
	'Headphones',
	'Home Audio',
	'Office Electronics',
	'Portable Audio and Video',
	'Security and Surveillance',
	'Service Plans',
	'Television and Video',
	'Video Game Consoles and Accessories',
	'Video Projectors',
	'Wearable Technology',
	'eBook Readers and Accessories',
	'Monitors',
	'Laptop Accessories',
	'Servers'
];
